require File.expand_path(File.join(__dir__, '../node_modules/react-native/scripts/react_native_pods'))

platform :ios, '15.1'

prepare_react_native_project!

# Ensure Firebase can be linked properly
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
else
  use_frameworks! :linkage => :static 
  $RNFirebaseAsStaticFramework = true 
end

target 'NARA' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Permissions - add if you use react-native-permissions
pod 'RNPermissions', :path => '../node_modules/react-native-permissions'


  # Firebase dependencies
  pod 'GoogleUtilities', :modular_headers => true
  pod 'Firebase/Core', :modular_headers => true
  pod 'Firebase/Messaging', :modular_headers => true

  target 'NARATests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    # Fix for use_frameworks! with Firebase
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end
